# Generated by Django 4.0.1 on 2022-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
