# Generated by Django 4.0.1 on 2022-01-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atfapp', '0003_alter_transaction_fingerprint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
