# Generated by Django 4.0.1 on 2022-01-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atfapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
